<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsersWithoutRole($role)
    {
        return $this->createQueryBuilder('user')
            ->andWhere('user.role <> :role')
            ->setParameter('role', $role)
            ->getQuery()
            ->getResult()
            ;
    }

    public function findChoiceModules($module)
    {
        return $this->createQueryBuilder('u')
            ->where('u.chosenModule LIKE :module')
            ->setParameter('module', '%"'.$module.'"%')
            ->getQuery()
            ->getResult();
    }
}
