security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_USER:        ROLE_USER
            ROLE_ADMIN:       [ROLE_USER, ROLE_ADMIN]

    providers:
        user_db_provider:
            entity:
                class: AppBundle:User
                property: email


    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: user_db_provider
                check_path: /login_check
                login_path: /login
                default_target_path: /test
                username_parameter: _username
                password_parameter: _password
            logout:
                path: /logout
                target: /
            anonymous: true


    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/test, role: ROLE_USER }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }



